global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "bankops_api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics

  - job_name: "bankops_ingestion"
    static_configs:
      - targets: ["ingestion:8001"]
    metrics_path: /metrics
